create table users (
    id bigint generated by default as identity constraint users_pkey primary key,
    create_at timestamp not null,
    updated_at timestamp,
    age int4,
    email varchar(200) unique,
    name varchar(500),
    password varchar(200),
    role int4
);
create table phones (
    id bigint generated by default as identity constraint phones_pkey primary key,
    create_at timestamp not null,
    updated_at timestamp,
    value varchar(100) unique,
    user_id bigint not null references users(id) on delete cascade
);
create table profiles (
    id bigint generated by default as identity constraint profiles_pkey primary key,
    create_at timestamp not null,
    updated_at timestamp,
    cash numeric(19, 2),
    percent numeric(19, 2),
    user_id bigint not null unique references users(id) on delete cascade
);

create table refresh_tokens (
    id bigint generated by default as identity constraint refresh_tokens_pkey primary key,
    create_at timestamp not null,
    updated_at timestamp,
    expire_date timestamp not null,
    token varchar(600) not null unique,
    user_id bigint not null references users(id)
);
